version: '3.4'

services:
  webapplication:
    image: ${DOCKER_REGISTRY-}webapplication
    profiles: [web]
    depends_on:
        - mssql
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    profiles: [web]
    container_name: mssql
    mem_limit: 2Gb
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=123456!Aa
    volumes:
        - mssql:/var/opt/mssql

volumes:
  mssql:
